# DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# SUPABASE STORAGE
supabase.url=https://jcigroanxweuzbkmqbib.supabase.co
supabase.key=${SUPABASE_SECRET_KEY}

# BUCKETS
supabase.bucket.verificaciones=verificacion-docs
supabase.bucket.eventos=eventos-images
supabase.bucket.categorias=categorias-images

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=20
spring.jpa.open-in-view=false

# HIKARI
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000